let a = 10
let b = 2

try {

    console.log("Soma: ", a + b)

} catch(error) {

    console.log("Erro: ", error)

}